name: Build and deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist/'

      # - name: Deploy
      #   run: |
      #     git config --global user.name $user_name
      #     git config --global user.email $user_email
      #     git remote set-url origin https://${github_token}@github.com/${repository}
      #     npx gh-pages -d dist
      #   env:
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
      #     github_token: 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
      #     repository: ${{ github.repository }}
